//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteAdminConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemoteAdminConsole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _checked {
            get {
                object obj = ResourceManager.GetObject("_checked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _unchecked {
            get {
                object obj = ResourceManager.GetObject("_unchecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ac {
            get {
                object obj = ResourceManager.GetObject("ac", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap adminconsole {
            get {
                object obj = ResourceManager.GetObject("adminconsole", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear_left {
            get {
                object obj = ResourceManager.GetObject("clear_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_0 {
            get {
                object obj = ResourceManager.GetObject("item_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -48`Platinum Bow`0`1`99`0`false`1
        ///-47`Platinum Hammer`0`1`7`0`false`0
        ///-46`Platinum Axe`0`1`10`0`false`0
        ///-45`Platinum Shortsword`0`1`6`0`false`0
        ///-44`Platinum Broadsword`0`1`4`0`false`0
        ///-43`Platinum Pickaxe`0`1`1`0`false`0
        ///-42`Tungsten Bow`0`1`99`0`false`1
        ///-41`Tungsten Hammer`0`1`7`0`false`0
        ///-40`Tungsten Axe`0`1`10`0`false`0
        ///-39`Tungsten Shortsword`0`1`6`0`false`0
        ///-38`Tungsten Broadsword`0`1`4`0`false`0
        ///-37`Tungsten Pickaxe`0`1`1`0`false`0
        ///-36`Lead Bow`0`1`99`0`false`1
        ///-35`Lead Hammer`0`1`7`0`fal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string itemlist {
            get {
                return ResourceManager.GetString("itemlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string itemlistsorted {
            get {
                return ResourceManager.GetString("itemlistsorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large:1
        ///Massive:2
        ///Dangerous:3
        ///Savage:4
        ///Sharp:5
        ///Pointy:6
        ///Tiny:7
        ///Terrible:8
        ///Small:9
        ///Dull:10
        ///Unhappy:11
        ///Bulky:12
        ///Shameful:13
        ///Heavy:14
        ///Light:15
        ///Sighted:16
        ///Rapid:17
        ///Hasty:18
        ///Intimidating:19
        ///Deadly:20
        ///Staunch:21
        ///Awful:22
        ///poethargic:23
        ///Awkward:24
        ///Powerful:25
        ///Mystic:26
        ///Adept:27
        ///Masterful:28
        ///Inept:29
        ///Ignorant:30
        ///Deranged:31
        ///Intense:32
        ///Taboo:33
        ///Celestial:34
        ///Furious:35
        ///Keen:36
        ///Superior:37
        ///Forceful:38
        ///Broken:39
        ///Damaged:40
        ///Shoddy:41
        ///Quick:42
        ///Deadly:43
        ///Agile:44
        ///Nimble:45
        ///Murde [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string prefixlist {
            get {
                return ResourceManager.GetString("prefixlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sprite {
            get {
                object obj = ResourceManager.GetObject("sprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sprite1 {
            get {
                object obj = ResourceManager.GetObject("sprite1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
